name: schmidt.yml
on:
  pull_request:
    types: [ opened, synchronize ]
  pull_request_review_comment:
    types: [ created ]

jobs:
  review:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'pull_request') ||
      ((github.event_name == 'pull_request_review_comment') && contains(github.event.comment.body, '/why'))
    steps:
      - uses: actions/checkout@v4
      - name: AI PR Review
        uses: vadim-heyworld/frau-schmidt@v0.6.7-alpha
        with:
          openai-api-key: ${{ secrets.FRAU_SCHMIDT_OPENAI_API_KEY }}
          project-name: 'tms'
          openai-model: 'gpt-4o'
          app-id: ${{ secrets.FRAU_SCHMIDT_APP_ID }}
          private-key: ${{ secrets.FRAU_SCHMIDT_APP_PRIVATE_KEY }}
          installation-id: ${{ secrets.FRAU_SCHMIDT_APP_INSTALLATION_ID }}
          full-scan: 'true'
          enable-replies: 'true'
          include-project-prompts-in-replies: 'true'
